name: Deploy Frontend to EC2

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/tinyurl-frontend

            git fetch origin
            git checkout prod
            git reset --hard origin/prod

            npm ci
            npm run build

            sudo cp -r dist/. /var/www/tinyurl-frontend/